//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory.Web.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; Success.
        /// </summary>
        public static string @__Success {
            get {
                return ResourceManager.GetString("\' Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; to User..
        /// </summary>
        public static string @__to_User_ {
            get {
                return ResourceManager.GetString("\' to User.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; 2025 - Inventory - .
        /// </summary>
        public static string _copy__2025___Inventory__ {
            get {
                return ResourceManager.GetString("&copy; 2025 - Inventory -", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to Cart.
        /// </summary>
        public static string AddedToCart {
            get {
                return ResourceManager.GetString("AddedToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to Favorite List.
        /// </summary>
        public static string AddedToFavorite {
            get {
                return ResourceManager.GetString("AddedToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Quantity.
        /// </summary>
        public static string AddQuantity {
            get {
                return ResourceManager.GetString("AddQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string An_error_occurred_while_processing_your_request_ {
            get {
                return ResourceManager.GetString("An error occurred while processing your request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and restarting the app..
        /// </summary>
        public static string and_restarting_the_app_ {
            get {
                return ResourceManager.GetString("and restarting the app.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete {
            get {
                return ResourceManager.GetString("Are you sure you want to delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to building Web apps with ASP.NET Core..
        /// </summary>
        public static string building_Web_apps_with_ASP_NET_Core_ {
            get {
                return ResourceManager.GetString("building Web apps with ASP.NET Core.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Delete Failed.
        /// </summary>
        public static string CartDeleteFailed {
            get {
                return ResourceManager.GetString("CartDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart item not found.
        /// </summary>
        public static string CartItemNotFound {
            get {
                return ResourceManager.GetString("CartItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Update Failed.
        /// </summary>
        public static string CartUpdateFailed {
            get {
                return ResourceManager.GetString("CartUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Deleted.
        /// </summary>
        public static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Category.
        /// </summary>
        public static string Create_a_New_Category {
            get {
                return ResourceManager.GetString("Create a New Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Product.
        /// </summary>
        public static string Create_a_New_Product {
            get {
                return ResourceManager.GetString("Create a New Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Register.
        /// </summary>
        public static string Create_a_New_Register {
            get {
                return ResourceManager.GetString("Create a New Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Role.
        /// </summary>
        public static string Create_a_New_Role {
            get {
                return ResourceManager.GetString("Create a New Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string CreateCategory {
            get {
                return ResourceManager.GetString("CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created &apos;.
        /// </summary>
        public static string Created__ {
            get {
                return ResourceManager.GetString("Created \'", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Category.
        /// </summary>
        public static string CreatedCategory {
            get {
                return ResourceManager.GetString("CreatedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Created.
        /// </summary>
        public static string CreatedProduct {
            get {
                return ResourceManager.GetString("CreatedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Created.
        /// </summary>
        public static string CreatedRole {
            get {
                return ResourceManager.GetString("CreatedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        public static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string Delete_Category {
            get {
                return ResourceManager.GetString("Delete Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        public static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Mode.
        /// </summary>
        public static string Development_Mode {
            get {
                return ResourceManager.GetString("Development Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited Category.
        /// </summary>
        public static string EditedCategory {
            get {
                return ResourceManager.GetString("EditedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Edited .
        /// </summary>
        public static string EditedProduct {
            get {
                return ResourceManager.GetString("EditedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  environment by setting the .
        /// </summary>
        public static string environment_by_setting_the {
            get {
                return ResourceManager.GetString("environment by setting the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment variable to.
        /// </summary>
        public static string environment_variable_to {
            get {
                return ResourceManager.GetString("environment variable to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  environment will display more detailed information about the error that occurred..
        /// </summary>
        public static string environment_will_display_more_detailed_information_about_the_error_that_occurred_ {
            get {
                return ResourceManager.GetString("environment will display more detailed information about the error that occurred." +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string Error_ {
            get {
                return ResourceManager.GetString("Error.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to assign Role &apos;.
        /// </summary>
        public static string Failed_to_assign_Role__ {
            get {
                return ResourceManager.GetString("Failed to assign Role \'", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Create User.
        /// </summary>
        public static string FailedToCreateUser {
            get {
                return ResourceManager.GetString("FailedToCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Update Role.
        /// </summary>
        public static string FailedToUpdateRole {
            get {
                return ResourceManager.GetString("FailedToUpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Img {
            get {
                return ResourceManager.GetString("Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CartItem.
        /// </summary>
        public static string InvalidCartItem {
            get {
                return ResourceManager.GetString("InvalidCartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the .
        /// </summary>
        public static string It_can_result_in_displaying_sensitive_information_from_exceptions_to_end_users__For_local_debugging__enable_the {
            get {
                return ResourceManager.GetString("It can result in displaying sensitive information from exceptions to end users. F" +
                        "or local debugging, enable the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Removed.
        /// </summary>
        public static string ItemRemoved {
            get {
                return ResourceManager.GetString("ItemRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item removed from Cart.
        /// </summary>
        public static string ItemRemovedFromCart {
            get {
                return ResourceManager.GetString("ItemRemovedFromCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JD.
        /// </summary>
        public static string JD {
            get {
                return ResourceManager.GetString("JD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about.
        /// </summary>
        public static string Learn_about {
            get {
                return ResourceManager.GetString("Learn about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Success.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Success.
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cart.
        /// </summary>
        public static string MyCart {
            get {
                return ResourceManager.GetString("MyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favorites.
        /// </summary>
        public static string MyFavorites {
            get {
                return ResourceManager.GetString("MyFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_ {
            get {
                return ResourceManager.GetString("Name ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Role.
        /// </summary>
        public static string NameRole {
            get {
                return ResourceManager.GetString("NameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite products yet..
        /// </summary>
        public static string No_favorite_products_yet_ {
            get {
                return ResourceManager.GetString("No favorite products yet.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorites found..
        /// </summary>
        public static string No_favorites_found_ {
            get {
                return ResourceManager.GetString("No favorites found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products in cart yet..
        /// </summary>
        public static string No_products_in_cart_yet_ {
            get {
                return ResourceManager.GetString("No products in cart yet.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not foundRole.
        /// </summary>
        public static string NotFoundRole {
            get {
                return ResourceManager.GetString("NotFoundRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found Role ID.
        /// </summary>
        public static string NotFoundRoleId {
            get {
                return ResourceManager.GetString("NotFoundRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Type.
        /// </summary>
        public static string PowerType {
            get {
                return ResourceManager.GetString("PowerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string Price_ {
            get {
                return ResourceManager.GetString("Price:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Product Deleted.
        /// </summary>
        public static string ProductDeleted {
            get {
                return ResourceManager.GetString("ProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Updated.
        /// </summary>
        public static string QuantityUpdated {
            get {
                return ResourceManager.GetString("QuantityUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Favorite From List.
        /// </summary>
        public static string RemovedFavoriteFromList {
            get {
                return ResourceManager.GetString("RemovedFavoriteFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed From Cart.
        /// </summary>
        public static string RemovedFromCart {
            get {
                return ResourceManager.GetString("RemovedFromCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from favorites.
        /// </summary>
        public static string RemovedFromFavorite {
            get {
                return ResourceManager.GetString("RemovedFromFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID:.
        /// </summary>
        public static string Request_ID_ {
            get {
                return ResourceManager.GetString("Request ID:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Deleted.
        /// </summary>
        public static string RoleDeleted {
            get {
                return ResourceManager.GetString("RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtracted Quantity.
        /// </summary>
        public static string SubtractQuantity {
            get {
                return ResourceManager.GetString("SubtractQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swapping to .
        /// </summary>
        public static string Swapping_to {
            get {
                return ResourceManager.GetString("Swapping to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Dashboard.
        /// </summary>
        public static string System_Dashboard {
            get {
                return ResourceManager.GetString("System Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Development environment shouldn&apos;t be enabled for deployed applications..
        /// </summary>
        public static string The_Development_environment_shouldn_t_be_enabled_for_deployed_applications_ {
            get {
                return ResourceManager.GetString("The Development environment shouldn\'t be enabled for deployed applications.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this page to detail your site&apos;s privacy policy..
        /// </summary>
        public static string this_page_to_detail_your_site_s_privacy_policy_ {
            get {
                return ResourceManager.GetString("this page to detail your site\'s privacy policy.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price:.
        /// </summary>
        public static string TotalPrice_ {
            get {
                return ResourceManager.GetString("TotalPrice:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Updated.
        /// </summary>
        public static string UpdatedRole {
            get {
                return ResourceManager.GetString("UpdatedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed.
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
